import os
from config import config as base_config

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = BASE_DIR

DATA_DIR = base_config.PROCESSED_DATA_DIR
METADATA_FILE = base_config.METADATA_FILE
MAX_FILE_SIZE = base_config.DEFAULT_MAX_FILE_SIZE

MODEL_DIR = os.path.join(BASE_DIR, "saved_models")
REPORT_DIR = os.path.join(BASE_DIR, "reports")
CACHE_DIR = os.path.join(BASE_DIR, "cache")
HARD_NEGATIVE_POOL_PATH = os.path.join(BASE_DIR, "hard_negative_pool.json")
ONNX_MODEL_DIR = os.path.join(MODEL_DIR, "onnx")
ONNX_ENABLED = False
ONNX_PROVIDERS = ["CPUExecutionProvider"]

NGRAM_SPECS = [(2, 512), (3, 512)]
NGRAM_SCALE = 1.0

STACKING_FOLDS = 3
ENSEMBLE_SEEDS = [17, 31, 47]

CALIBRATION_METHOD = "isotonic"
THRESHOLD_MAX_FPR = None
THRESHOLD_FP_WEIGHT = 5.0
THRESHOLD_FN_WEIGHT = 1.0

COST_POS_WEIGHT = 1.0
COST_NEG_WEIGHT = 3.0
POS_WEIGHT_SCALE = 0.01
HARD_NEGATIVE_WEIGHT = 5.0
HARD_NEGATIVE_MAX = 5000

GATING_HIDDEN_DIM = 256
GATING_EPOCHS = 10
GATING_BATCH_SIZE = 128
GATING_LEARNING_RATE = 0.001
GATING_THRESHOLD = 0.5

TIME_SPLIT_TEST_RATIO = base_config.DEFAULT_TEST_SIZE
TIME_SPLIT_VAL_RATIO = base_config.DEFAULT_VAL_SIZE
RANDOM_STATE = base_config.DEFAULT_RANDOM_STATE

LIGHTGBM_NUM_ROUNDS = base_config.DEFAULT_NUM_BOOST_ROUND
LIGHTGBM_EARLY_STOPPING = base_config.DEFAULT_EARLY_STOPPING_ROUNDS
